version: '3.1'
services:
  springboot:
    image: mylandmarktech/maven-web-app:VERSION
    restart: always
    ports:
    - 9090:8080
    networks:
    - mavenappbridge
networks:
  mavenappbridge:
